server:
  port: 9200

spring:
  application:
    name: cloud-gateway9200
  cloud:
    gateway:
      #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      discovery:
        locator:
          enabled: true
      #路由配置
      routes:
        - id: payment_route_1
#          uri: http://localhost:8001 #匹配后提供服务的地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/** #断言，路径相匹配的进行路由

        - id: payment_route_2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/timeout

        # 测试动态路由
        - id: payment_route_3
          uri: lb://cloud-payment-service
          filters:
#            - AddRequestParameter=X-Request-Id, 1024 #过滤器工厂会在匹配的请求头上加上一对请求头
          predicates:
            - Path=/gateway
#            - After= # ZonedDateTime,在地址匹配之后，再匹配一些条件，如时间，Cookie，主机，方法...
#            - Before=
#            - Between=
#            - Cookie=
#            - Header=
#            - Host=
#            - Method=
#            - Query=
#            - ReadBodyPredicateFactory=
#            - RemoteAddr=
#            - Weight=
#            - CloudFoundryRouteService=

eureka:
  instance:
    instance-id: gateway9200
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka #Eureka Server地址
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #Eureka Server集群环境